[package]
name = "seed"
version = "0.4.1"
description = "A Rust framework for creating web apps, using WebAssembly"
authors = ["DavidOConnor <david.alan.oconnor@gmail.com>"]
license = "MIT"
repository = "https://github.com/David-OConnor/seed"
homepage = "https://seed-rs.org"
documentation = "https://docs.rs/seed"
readme = "README.md"
keywords = ["wasm", "webassembly", "frontend", "framework", "web"]
categories = ["wasm", "web-programming"]
edition = "2018"

build = "build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[build-dependencies]
version_check = "^0.9.1"

[dev-dependencies]
wasm-bindgen-test = "0.2.50" # NOTE: keep in sync with wasm-bindgen version

[dependencies]
console_error_panic_hook = "^0.1.6"
enclose = "^1.1.6"
futures = "^0.1.27"
gloo-timers = "^0.1.0"
indexmap = "^1.0.2"
js-sys = "0.3.27"
pulldown-cmark = "^0.5.2"
serde = { version = "^1.0.92", features = ['derive'] }
serde_json = "^1.0.39"
# NOTE: keep in sync with wasm-bindgen-test version
wasm-bindgen = {version = "0.2.50", features = ["serde-serialize"]}
wasm-bindgen-futures = "0.3.22"
# @TODO: remove once we can use entities without `Debug` in `log!` and `error!` on `stable` Rust.
# https://github.com/Centril/rfcs/blob/rfc/quick-debug-macro/text/0000-quick-debug-macro.md#types-which-are-not-debug
dbg = "1.0.4"

[dependencies.web-sys]
version = "0.3.27"
features = [
    "AbortController",
    "AbortSignal",
    "CustomEvent",
    "CustomEventInit",
    "Document",
    "DomException",
    "Element",
    "Event",
    "EventTarget",
    "HashChangeEvent",
    "Headers",
    "History",
    "HtmlElement",
    "HtmlCollection",
    "HtmlInputElement",
    "HtmlMenuItemElement",
    "HtmlProgressElement",
    "HtmlOptionElement",
    "HtmlDataElement",
    "HtmlMeterElement",
    "HtmlLiElement",
    "HtmlOutputElement",
    "HtmlParamElement",
    "HtmlTextAreaElement",
    "HtmlSelectElement",
    "HtmlButtonElement",
    "Location",
    "MouseEvent",
    "Node",
    "NodeList",
    "Performance",
    "PointerEvent",
    "PopStateEvent",
    "ReferrerPolicy",
    "Request",
    "RequestCache",
    "RequestCredentials",
    "RequestInit",
    "RequestMode",
    "RequestRedirect",
    "Response",
    "Storage",
    "Text",
    "console",
    "Window",
    "KeyboardEvent",
    "InputEvent",
]

[workspace]
members = [
    "examples/animation_frame",
    "examples/counter",
    "examples/drop",
    # "examples/homepage",   # isn't Rust project
    "examples/mathjax",
    "examples/orders",
    # "examples/server_integration",   # has own workspace
    "examples/server_interaction",
#    "examples/server_interaction_detailed",  # has own workspace
    "examples/todomvc",
    "examples/update_from_js",
    "examples/user_media",
    "examples/websocket",
    "examples/window_events",
    "examples/routes-bug",
]

exclude = [
    # it has own workspace
    "examples/server_integration",
    "examples/server_interaction_detailed",
]
